import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { rootDirectory } from "./config.ts";
import { listFiles } from "./files.ts";

let digestPromise: Promise<string> | undefined;

// Bind every manifest to the exact converter implementation and dependency
// graph that produced it. Tests are intentionally excluded: changing a fixture
// does not change generated bytes, while every runtime TypeScript module does.
export function currentGeneratorDigest(): Promise<string> {
  digestPromise ??= computeGeneratorDigest();
  return digestPromise;
}

async function computeGeneratorDigest(): Promise<string> {
  const sourceFiles = (await listFiles(path.join(rootDirectory, "src")))
    .filter((file) => file.endsWith(".ts") && !file.endsWith(".test.ts"))
    .map((file) => `src/${file}`);
  const files = [
    ...sourceFiles,
    "package.json",
    "bun.lock",
    "tsconfig.json",
  ].sort(compareCodePoints);
  const digest = createHash("sha256");
  for (const relativePath of files) {
    digest.update(relativePath);
    digest.update("\0");
    digest.update(await readFile(path.join(rootDirectory, relativePath)));
    digest.update("\n");
  }
  return digest.digest("hex");
}

function compareCodePoints(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}
